server:
  port: 8080

spring:
  application:
    name: recipetacle

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=recipetacle}
    username: ${DB_USER:recipetacle}
    password: ${DB_PASS:recipetacle}

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:*}